# Generated by Django 4.2.16 on 2024-12-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yms_edit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yard',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yard',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
