# Generated by Django 4.2.16 on 2024-12-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yms_edit', '0002_yard_latitude_yard_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='yard',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
