# Generated by Django 4.2.16 on 2024-11-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yms_edit", "0002_alter_site_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="capacity",
            field=models.PositiveIntegerField(),
        ),
    ]
