# Generated by Django 4.2.16 on 2024-12-02 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('yms_edit', '0003_yard_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=50)),
                ('movement_time', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('arrival_yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='yms_edit.yard')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('departure_yard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='yms_edit.yard')),
            ],
        ),
    ]
