# Generated by Django 4.2.16 on 2024-11-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("yms_edit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("Truck", "Truck"),
                            ("Chassis", "Chassis"),
                            ("Container", "Container"),
                            ("Trailer", "Trailer"),
                            ("PersonalVehicle", "Personal Vehicle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("equipment", models.PositiveIntegerField(blank=True, null=True)),
                ("movement_time", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField(blank=True, null=True)),
                (
                    "arrival_yard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_arrived",
                        to="yms_edit.yard",
                    ),
                ),
                (
                    "departure_yard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_departed",
                        to="yms_edit.yard",
                    ),
                ),
            ],
        ),
    ]
